### PR TITLE
v3.1.9

### PR DESCRIPTION
**Pull request by sonvnn**

### CODE REVIEW

**Review by sonvnn — COMMENTED** [review]
@felixkat Please help me review this code. If it's work please help me approve this with comment. 
Thanks,
Sonny

**Review by sonvnn — COMMENTED** [review]
@rinka88 Please help me review load Single module feature. If this works, please help me approve this review

**Comment by rinka88** [comment]
> @rinka88Пожалуйста, помогите мне просмотреть функцию «Загрузить один модуль». Если это работает, пожалуйста, помогите мне одобрить этот обзор

Module selection works fine. Modules are displayed on the site. I just noticed that the Style Module is not used in both cases. And in positions and module selection. And how do I approve a review?

**Comment by sonvnn** [comment]
> > @rinka88Пожалуйста, помогите мне просмотреть функцию «Загрузить один модуль». Если это работает, пожалуйста, помогите мне одобрить этот обзор
> 
> Module selection works fine. Modules are displayed on the site. I just noticed that the Style Module is not used in both cases. And in positions and module selection. And how do I approve a review?

Submit a review and approve here
Screen Shot 2024-11-29 at 16 27 35

**Review by felixkat — APPROVED** [review]
Everything I have tested so far is all working.

**Comment by rinka88** [comment]
Все, что я проверил, работает.

**Review by rinka88 — COMMENTED** [review]
Everything works. Great.

**Comment by sonvnn** [comment]
@rinka88 you have to select approve radiobox to approve this.

**Review by rinka88 — APPROVED** [review]
Everything works. Great.

**Comment by C-G-White** [comment]
Sonvnn,  sorry but this is my first time using the commenting / review system on Github having reported the issue.  Where do I download the updated version 3.1.9?  I am damned if I can see the place to download it!!!  All the best.  Regards,  Chris.

**Review by C-G-White — APPROVED** [review]
Hi this has fixed the issue with the menu dropdown.

**Comment by WM-Loose** [comment]
With 3.1.9 the following errors appear when you open your own module in the frontend and then click save.




If I go back to 3.1.8 everything is fine.
I had that before but you couldn't reproduce it Sonny.

**Comment by sonvnn** [comment]
> With 3.1.9 the following errors appear when you open your own module in the frontend and then click save:
> 
>   
> 
> If I go back to 3.1.8 everything is fine. I had that before but you couldn't reproduce it Sonny.

I fixed this issue on https://github.com/templaza/astroid-framework/commit/711578b9efa0350206fcc3e6b9ab2dba0772a1c5
Please download v3-branch and retest again.

**Comment by WM-Loose** [comment]
It works now vith v3-branch.

**Pull request merged**
